language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_install:
  - sudo easy_install Pygments

before_script:
  - composer require --no-update satooshi/php-coveralls:dev-master sensiolabs/security-checker:dev-master
  - composer update --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml
  - php vendor/bin/security-checker security:check composer.lock

after_script:
  - php vendor/bin/coveralls
